"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { demoAircraft, driftAircraft, type AircraftState } from "@/services/aircraftService";

type View="home"|"about"|"stages"|"join"|"lobby"|"flight"|"fishing"|"redline"|"same"|"deja"|"leaderboard"|"admin";
const stages=[
  ["01","♦","FLIGHT 404","THE LAST SEAT","20 → 15","LOGIC · OBSERVATION · RISK","/game/flight-404"],
  ["02","♠","FISHING","SURVIVE THE JACK","15 → 10","STEALTH · TIMING · SURVIVAL","/game/fishing"],
  ["03","♠","REDLINE","ONE LINE. NO RETURN.","10 → 7","REFLEX · PATTERN RECOGNITION","/game/redline"],
  ["04","♣","SAME PAGE","DIFFERENT PERSPECTIVES.","7 → 4","TRUST · PSYCHOLOGY · TEAMWORK","/game/same-page"],
  ["05","♥","DEJA VU","SAME MOMENT. DIFFERENT TRUTH.","4 → 1","MEMORY · DEDUCTION · TRUST","/game/deja-vu"],
] as const;
function Shell({children}:{children:React.ReactNode}) { const [open,setOpen]=useState(false); return <div className="shell"><nav className="nav"><Link href="/" className="brand">SKYNET<small>BorderLand</small></Link><button className="button mobile-nav" onClick={()=>setOpen(!open)} aria-expanded={open}>MENU</button><div className={`navlinks ${open?"open":""}`}><Link href="/">HOME</Link><Link href="/about">ABOUT</Link><Link href="/stages">STAGES</Link><Link href="/leaderboard">LEADERBOARD</Link><Link href="/about#faq">FAQ</Link></div></nav>{children}</div> }
function Telemetry({aircraft}:{aircraft:AircraftState}) { return <aside className="telemetry"><div className="meta">Live aircraft <span className="status">{aircraft.source.toUpperCase()}</span></div><h3 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0"}}>{aircraft.callsign}</h3><div className="telemetry-grid"><div><span className="meta">ALT</span><b>{aircraft.altitude.toLocaleString()} FT</b></div><div><span className="meta">SPD</span><b>{aircraft.speed} KT</b></div><div><span className="meta">HDG</span><b>{String(aircraft.heading).padStart(3,"0")}°</b></div></div><p className="meta" style={{marginTop:17}}>POS {aircraft.latitude.toFixed(2)} / {aircraft.longitude.toFixed(2)} · TRACKING</p></aside> }
function UseAircraft(){const [aircraft,setAircraft]=useState(demoAircraft);useEffect(()=>{const id=setInterval(()=>setAircraft(a=>driftAircraft(a)),3000);return()=>clearInterval(id)},[]);return aircraft}
function Header({stage}:{stage:(typeof stages)[number]}){return <header className="game-head"><div><div className="eyebrow">Stage {stage[0]} · {stage[1]} · {stage[5]}</div><h1 className="game-title">{stage[2]} <i style={{color:"#a82925"}}>{stage[3]}</i></h1></div><div className="timer">05:00</div></header>}
function Home(){const aircraft=UseAircraft();return <Shell><main className="main hero"><section><div className="eyebrow">HalfCyphyx · classified survival system</div><h1 className="display">SKYNET <span>BorderLand</span></h1><p className="subtitle">THE SKY IS THE GAME BOARD.<br/><br/>20 PLAYERS. 5 TRIALS. 1 SURVIVOR. Aircraft telemetry is not decoration. It is the rulebook.</p><div className="hero-actions"><Link className="button red" href="/join">ENTER HACKER LAND</Link><Link className="button" href="/stages">VIEW THE TRIALS</Link></div></section><section><div className="radar" aria-label="Aircraft surveillance radar"/><Telemetry aircraft={aircraft}/></section></main></Shell>}
function Stages(){return <Shell><main className="main"><div className="eyebrow">Trial registry · 20 enter · 1 escapes</div><h1 className="page-title">THE FIVE TRIALS</h1><div className="grid three">{stages.map(s=><Link href={s[6]} className="stage-card" key={s[0]}><div><div className="eyebrow">Stage {s[0]} · {s[4]}</div><div className="stage-suit">{s[1]}</div><h2>{s[2]}</h2><p>{s[3]}</p></div><div className="meta">{s[5]}<br/>STATUS · STANDBY</div></Link>)}</div></main></Shell>}
function Join(){const [name,setName]=useState("");const [done,setDone]=useState(false);return <Shell><main className="main" style={{maxWidth:650}}><div className="eyebrow">SKYNET BorderLand</div><h1 className="page-title">PLAYER<br/>IDENTIFICATION</h1>{done?<div className="terminal">CONNECTION ESTABLISHED<br/><br/><strong style={{color:"#e7e0d3",fontSize:28}}>PLAYER 07 · {name.toUpperCase()}</strong><br/><br/>SESSION LINKED. REPORT TO THE LOBBY.</div>:<form onSubmit={e=>{e.preventDefault();if(name.trim())setDone(true)}}><label className="meta" htmlFor="codename">Enter codename</label><input id="codename" value={name} onChange={e=>setName(e.target.value)} maxLength={16} required style={{display:"block",width:"100%",background:"transparent",color:"#e7e0d3",border:"0",borderBottom:"1px solid #958f87",font:"32px Georgia,serif",padding:"13px 0",margin:"12px 0 22px"}}/><p className="meta" style={{marginBottom:25}}>Player number · auto assigned</p><button className="button red">CONNECT</button></form>}</main></Shell>}
function Lobby(){const players=Array.from({length:20},(_,i)=>i<17?i%3===0?"READY":"ONLINE":"AWAITING");return <Shell><main className="main"><div className="eyebrow">Connection status · demo node</div><h1 className="page-title">TRIAL INITIALIZATION</h1><div className="grid two"><section className="board"><h2 className="panel-title">PLAYERS CONNECTED · 17 / 20</h2><div className="grid three">{players.map((p,i)=><div className="stat" key={i}><span className="meta">{String(i+1).padStart(2,"0")}</span><strong style={{fontSize:15,color:p==="AWAITING"?"#958f87":"#e7e0d3"}}>{p}</strong></div>)}</div></section><section className="terminal">SERVER · <span className="status">DEMO MODE</span><br/>AIRCRAFT FEED · TRACKING<br/>GAME MASTER · ONLINE<br/><br/>ALL CONNECTIONS ESTABLISHED WHEN 20 OPERATIVES REPORT.<br/><br/><Link className="button red" href="/game/flight-404">INITIALIZE TRIAL</Link></section></div></main></Shell>}
function Flight(){const aircraft=UseAircraft(),[seat,setSeat]=useState<string>(),[locked,setLocked]=useState(false);return <Shell><main className="main"><Header stage={stages[0]}/><div className="game-layout"><section className="board"><h2 className="panel-title">CABIN ASSIGNMENT · ALTITUDE DETERMINES THE PATTERN</h2><p className="subtitle">Observe altitude, heading and speed. The aircraft has already chosen five unsafe positions.</p><div className="seatmap">{Array.from({length:20},(_,i)=>{const id=`${"ABCD"[i%4]}${Math.floor(i/4)+1}`;return <button key={id} className={`seat ${seat===id?"selected":""} ${locked&&seat===id?"locked":""}`} onClick={()=>!locked&&setSeat(id)}>{id}<br/>{locked&&seat===id?"LOCKED":"UNKNOWN"}</button>})}</div><button className="button red" disabled={!seat||locked} onClick={()=>setLocked(true)}>{locked?"SEAT LOCKED":"CONFIRM SEAT"}</button></section><Telemetry aircraft={aircraft}/></div></main></Shell>}
function Fishing(){const aircraft=UseAircraft(),[breath,setBreath]=useState(78),[surface,setSurface]=useState(false),[depth,setDepth]=useState(12.4);useEffect(()=>{const id=setInterval(()=>setBreath(x=>Math.max(0,Math.min(100,x+(surface?5:-2)))),900);return()=>clearInterval(id)},[surface]);return <Shell><main className="main"><Header stage={stages[1]}/><div className="game-layout"><section className="board lake"><h2 className="panel-title">UNDERWATER CHANNEL · JACK STATUS: {surface?"ALERT":"SEARCHING"}</h2><div style={{marginTop:150,position:"relative",zIndex:1}}><div className="meta">BREATH · {breath}%</div><div className="meter"><i style={{width:`${breath}%`}}/></div><p className="meta">DEPTH · {depth.toFixed(1)} M · DETECTION RISK · {surface?"HIGH":"LOW"}</p><div className="action-row"><button className="button red" onClick={()=>{setSurface(!surface);setDepth(d=>surface?d+3:Math.max(0,d-3))}}>{surface?"DIVE DEEPER":"SURFACE"}</button><button className="button" onClick={()=>setDepth(d=>d+1.2)}>MOVE</button></div></div></section><Telemetry aircraft={aircraft}/></div></main></Shell>}
function Redline(){const aircraft=UseAircraft(),[pos,setPos]=useState(0),[lives,setLives]=useState(3);const laser=(pos+aircraft.heading)%25;function move(n:number){const next=Math.max(0,Math.min(24,pos+n));setPos(next);if(next===laser)setLives(x=>Math.max(0,x-1))}return <Shell><main className="main"><Header stage={stages[2]}/><div className="game-layout"><section className="board"><h2 className="panel-title">SECURITY GRID · LIVES {lives} · USE ARROW CONTROLS</h2><div className="laser-grid">{Array.from({length:25},(_,i)=><div className={`cell ${i===pos?"player":""} ${i===laser?"laser":""}`} key={i}/>)}</div><div className="action-row"><button className="button" onClick={()=>move(-5)}>↑</button><button className="button" onClick={()=>move(-1)}>←</button><button className="button" onClick={()=>move(1)}>→</button><button className="button" onClick={()=>move(5)}>↓</button></div></section><Telemetry aircraft={aircraft}/></div></main></Shell>}
function Same(){const [answer,setAnswer]=useState<string>(),[reveal,setReveal]=useState(false);return <Shell><main className="main"><Header stage={stages[3]}/><section className="board" style={{maxWidth:760}}><div className="eyebrow">Private team channel · Question locked until submission</div><p className="question">WHICH AIRCRAFT IS TRAVELLING EAST?</p>{["A · HDG 090°","B · HDG 270°","C · HDG 180°","D · HDG 045°"].map(x=><button className={`button option ${answer===x?"selected":""}`} onClick={()=>!reveal&&setAnswer(x)} key={x}>{x}</button>)}<div className="action-row" style={{marginTop:20}}><button className="button red" disabled={!answer} onClick={()=>setReveal(true)}>{reveal?"ANSWER SUBMITTED":"SUBMIT PRIVATE ANSWER"}</button></div>{reveal&&<div className="terminal" style={{marginTop:20}}>WAITING FOR TEAM<br/><br/>PLAYER 01 → B<br/>PLAYER 02 → B<br/>PLAYER 03 → B<br/><br/><strong>ALL ANSWERS MATCH · TEAM SURVIVES</strong></div>}</section></main></Shell>}
function Deja(){const [phase,setPhase]=useState(1),[vote,setVote]=useState<string>();const data=[["A","31,000","420","090"],["B","27,000","380","270"],["C","40,000","460","180"],["D","19,000","310","045"]];return <Shell><main className="main"><Header stage={stages[4]}/><section className="board" style={{maxWidth:850}}>{phase===1?<><div className="eyebrow">Memory load · 00:30 · memorize</div><div className="memory-grid" style={{marginTop:22}}>{data.map(a=><div className="stat" key={a[0]}><span className="meta">Flight {a[0]}</span><strong>ALT {a[1]} FT</strong><p className="meta">SPD {a[2]} · HDG {a[3]}°</p></div>)}</div><button className="button red" style={{marginTop:22}} onClick={()=>setPhase(2)}>ERASE SNAPSHOT</button></>:<><div className="eyebrow">Memory leak · data lost</div><p className="question">WHICH AIRCRAFT WAS HIGHEST?</p>{data.map(a=><button className={`button option ${vote===a[0]?"selected":""}`} onClick={()=>setVote(a[0])} key={a[0]}>FLIGHT {a[0]}</button>)}<button className="button red" style={{marginTop:15}} onClick={()=>setPhase(3)} disabled={!vote}>{phase===3?"CONNECTION ACCEPTED · YOU SURVIVED":"LOCK MEMORY"}</button>{phase===3&&<p className="meta" style={{marginTop:18}}>ONE OF YOU REMEMBERS INCORRECTLY. VOTE SEALED.</p>}</>}</section></main></Shell>}
function About(){return <Shell><main className="main" style={{maxWidth:860}}><div className="eyebrow">System dossier</div><h1 className="page-title">WELCOME TO HACKER LAND</h1><p className="subtitle" style={{fontFamily:"Georgia,serif",fontSize:23}}>“You entered voluntarily. You will leave only if you survive.”</p><div className="grid two" style={{marginTop:38}}><div className="terminal">SKYNET: BorderLand is a five-stage survival system. Each trial translates live aircraft signals into a different human test: LOGIC, SURVIVAL, REFLEX, TRUST, and MEMORY.</div><div className="terminal">THE ADMIN<br/><br/>A presence behind the control room. It does not explain the rules. It observes what you do with them.</div></div><section id="faq" style={{marginTop:55}}><h2 className="page-title" style={{fontSize:43}}>FAQ</h2>{[["What is SKYNET BorderLand?","A multiplayer survival prototype structured around five connected trials."],["How many players can participate?","Twenty players enter. One survivor leaves."],["How does aircraft data affect the game?","Altitude, speed, heading and position alter each trial’s conditions."],["Can it run without live data?","Yes. Demo telemetry continues the full experience when an API is unavailable."],["What happens when eliminated?","Your connection is terminated for the session."],["How are winners determined?","The final survivor of Deja Vu is accepted by the system."]].map(x=><div className="stat" key={x[0]}><b>{x[0]}</b><p className="subtitle">{x[1]}</p></div>)}</section></main></Shell>}
function Leaderboard(){const rows=[["01","ALICE","5 / 5","9840","SURVIVOR"],["02","ZERO","4 / 5","8120","ELIMINATED"],["03","NOVA","4 / 5","7710","ELIMINATED"],["04","ECHO","3 / 5","6220","ELIMINATED"]];return <Shell><main className="main"><div className="eyebrow">Survivor registry</div><h1 className="page-title">LEADERBOARD</h1><section className="board"><table className="table"><thead><tr><th>RANK</th><th>CODENAME</th><th>STAGES SURVIVED</th><th>SCORE</th><th>STATUS</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={i} className={i===4?"status":""}>{x}</td>)}</tr>)}</tbody></table></section></main></Shell>}
function Admin(){const aircraft=UseAircraft(),[demo,setDemo]=useState(true),[paused,setPaused]=useState(false),[overlay,setOverlay]=useState(false);return <Shell><main className="main"><div className="eyebrow">Game Master console · restricted</div><h1 className="page-title">LIVE SESSION</h1><div className="grid two"><section className="board"><h2 className="panel-title">CURRENT STAGE · FLIGHT 404 · {paused?"PAUSED":"LIVE"}</h2><Telemetry aircraft={{...aircraft,source:demo?"demo":"live"}}/><div className="action-row" style={{marginTop:18}}><button className="button red" onClick={()=>setPaused(false)}>START STAGE</button><button className="button" onClick={()=>setPaused(!paused)}>{paused?"RESUME":"PAUSE"}</button><button className="button" onClick={()=>setDemo(!demo)}>USE {demo?"LIVE":"DEMO"} DATA</button><button className="button" onClick={()=>setOverlay(true)}>ELIMINATE PLAYER</button></div></section><section className="terminal">EVENT LOG<br/><br/>[22:14:08] AIRCRAFT UPDATE RECEIVED<br/>[22:14:04] PLAYER 07 LOCKED SEAT C3<br/>[22:13:59] STAGE START AUTHORIZED<br/>[22:13:55] DEMO ENGINE ACTIVE<br/><br/>CONNECTED PLAYERS · 17 / 20<br/>GAME TIMER · 05:00</section></div>{overlay&&<div className="overlay"><div className="overlay-content"><div className="eyebrow">System notice</div><h2>CONNECTION<br/>TERMINATED</h2><p>PLAYER 07 · DELETED FROM HACKER LAND</p><button className="button red" style={{marginTop:25}} onClick={()=>setOverlay(false)}>RESTORE SESSION</button></div></div>}</main></Shell>}
export function SystemPage({view}:{view:View}){return ({home:<Home/>,about:<About/>,stages:<Stages/>,join:<Join/>,lobby:<Lobby/>,flight:<Flight/>,fishing:<Fishing/>,redline:<Redline/>,same:<Same/>,deja:<Deja/>,leaderboard:<Leaderboard/>,admin:<Admin/>})[view]}
